apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  annotations:
    build.appstudio.openshift.io/application: test-app-ggmv
    build.appstudio.openshift.io/build: "true"
    build.appstudio.openshift.io/component: test-component--brgi
    build.appstudio.openshift.io/type: build
    build.appstudio.openshift.io/version: "0.1"
    pipelines.appstudio.openshift.io/type: build
  creationTimestamp: null
  name: test-component--brgi
  namespace: e2e-test-pipelines-byve
spec:
  namespaceSelector: {}
  resources: {}
  serviceAccountName: pipeline
  triggers:
  - bindings:
    - kind: ClusterTriggerBinding
      ref: github-push
    template:
      ref: test-component--brgi
status:
  configuration:
    generatedName: ""
